### ISSUE TITLE
Ubuntu packages fail to parse

### ISSUE THREAD

**Issue by cholcombe973** [kherge/recital#6]
I'm probably going to submit a PR for this but I just wanted to bring it to your attention.  This package version `3.8.7-ubuntu1~trusty1` fails to parse.  It's most likely the ~trusty1 bit on the end.

**Comment by kherge** [comment]
Unfortunately that doesn't follow [semantic versioning](http://semver.org/#spec-item-9) rules.

**Comment by cholcombe973** [comment]
Yeah I just realized after reading the rules that ubuntu and debian don't really follow them.  They're close but not exact.  I'll close this
